version: '3.1'
services:
  master:
    image: stephanevdb/vigilanteye-master:latest
    restart: unless-stopped
    ports:
      - "8666:8666"
      - "8666:8666/tcp6"
  worker:
    image: stephanevdb/vigilanteye-worker:latest
    restart: unless-stopped
    ports:
      - "8667:8667"
      - "8667:8667/tcp6"
    depends_on:
      - master
