version: '3.1'
services:
  master:
    image: stephanevdb/stephanevdb/vigilanteye-master:latest
    restart: unless-stopped
    ports:
      - "5080:3000"
  worker:
    image: stephanevdb/stephanevdb/vigilanteye-worker:latest
    restart: unless-stopped
    
    